### ISSUE TITLE
HDDCash Wallet

### ISSUE THREAD

**Issue by TheNetWhiz** [quetzalcoatl/blagominer#13]
When setup solo mining, miner will pull from wallet and submit. However, I keep getting this as a response: 

HDDCash: {"result":null,"error":{"code":-1,"message":"JSON value is not a string as expected"},"id":null}

Know of a solution?

**Comment by TheNetWhiz** [comment]
Any idea on this issue?

**Comment by quetzalcoatl** [comment]
Sorry, after I cleaned old issues, I didn't notice a new issue showed up.

This is a parsing error, if this is a response from the wallet, that means that the 'submit' request sent by the miner is invalid - it either lacks some required field, or that field is present but is a number, object, null, etc instead of carrying a text. That's a bit strange as I wouldn't expect HDDCash to change anything in the protocol, but who knows.

Could you try once again after ensuring these options are turned on in `miner.conf`:

    .....
    "Logging" : {
        "UseLog" : true,
        "logAllGetMiningInfos" : true,
        .....
    },
    "Debug": true,
    .....
    
Please run the miner for a short time, just to get that error, and then attach here that miner.conf (with your account/etc overwritten with zeroes or xxxx but please keep the original format you had there) and the log file, preferably zipped :)

I haven't tried playing with HDDCash, but I'll surely try to diagnose what's going on.

By the way, have you tried older versions like andzno1's? If it fails as well, then we probably have a protocol change. If it works, then maybe I screwed something in solo mode when I added HTTPS support and extra headers.

**Comment by quetzalcoatl** [comment]
Closed due to inactivity
