### ISSUE TITLE
Miner stuck in DL-resending loop when the pool responds with 200/OK but the response payload doesn't contain expected data ("Server error: 200 OK")

### ISSUE THREAD

**Issue by Zwurg** [quetzalcoatl/blagominer#26]
The Miner  misinterpreted the answer from the Burst Pool and send the last deadline every few seconds.
This trashes the miner window and the Pool. @quetzalcoatl

**Comment by quetzalcoatl** [comment]
Most probably, not really, but at first glance I do believe it looks like misinterpreting.  
It's hard to catch, but I've seen this happening once, but on another pool.  

When I saw it, the pool indeed responded with 200/OK, but the response did not contain the specific data that it should carry. Miner could not make 100% sure that the deadline has been accepted (response was 200 but did not match the protocol) so the DL was put back on to-be-sent queue and retried as it happens with any other error.

Well.. that's the base cause and the theory of what happened. As I said, I heard it happening once or two since I started working on this project, and I have seen it happen live just once. And indeed the miner locked up in retrying. However, I didn't manage to catch the response from the pool, so I had nothing to inspect. And I never have managed to reproduce the issue, not even randomly, so it has been put on a low-prio.

Thank you for reporting it. This will help me remember about re-writing the response parser and making it more resilient. A 200-class response that lacks the critical data is still an error, but it's all networking and may happen and miner should not fail this badly when the pool has some technical problems. Some exponential backoff could be added, some send-queue-purging on round-change, etc. Or even treating 200-class response as "fine, move along" regardless of protocol faults.. many solutions to pick from.

For now, if that's intermittent error, showing up once a year, it's on pause and To-Do list.

If it happens more often for you, please tell. Try to observe when it happens. Turn logging on, sanitize logs and attach here, maybe there's something interesting there. Maybe there's some problem with the pool itself or something changed in Burst protocol? Maybe the pool enabled some new extensions? Get in touch with other people using that pool (discord channels?), maybe other people also experience problems with that pool? Try another pool see if it happens there as well?

**Comment by VerbludSlon** [comment]
I can confirm the case for BURST pool.burstcoin.ro:

![200_OK_Lock_example](https://user-images.githubusercontent.com/74158429/99734075-47713680-2ad3-11eb-8a6e-f7132a57d87b.jpg)

**Comment by quetzalcoatl** [comment]
Thank you! I think I'll have some time during the weekend to check this out.

**Comment by quetzalcoatl** [comment]
Alright, while I still have a whole lot of waiting until my wallet synces up and allows me to rebind reward assignement to the pool.burstcoin.ro pool for testing, I was able to see what's going on on an unbound account - pool responds with http/403, and the miner goes crazy just the same, as expected, since that's DL delivery error and the miner has only a simple "retry asap" policy for that.

Anyways, I was able to observe what really happens, and it turns out that the miner parses that 403 response. Not that it matters much for the overall outcome, since it's 403, but the important part is how/why it fails to parse it.

The response was:

```
HTTP/1.1 403 Forbidden
Date: Fri, 27 Nov 2020 15:32:25 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 93
Connection: close
Set-Cookie: __cfduid=df571bf8ca73afe128069be01ee79fad31606491145; expires=Sun, 27-Dec-20 15:32:25 GMT; path=/; domain=.burstcoin.ro; HttpOnly; SameSite=Lax
X-Ratelimit-Limit: 3
X-Ratelimit-Remaining: 2
X-Ratelimit-Reset: 1
CF-Cache-Status: DYNAMIC
cf-request-id: 06abee9c0f0000ee48f7941000000001
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=hWxKgNk8RoQ5b3NlXAYIFLMJRHKTO%2Ba1NK7Q6zIjkPnYDaA0rxORnsqmAPZh0Hmdx%2BaWHGbtx1VesAb2YFQyCZzWS6c%2BQpTkwiXs9yxzVcYIvUIo17Xn"}],"group":"cf-nel","max_age":604800}
NEL: {"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 5f8ce6d9bc4fee48-CDG

{"errorCode":"1004","errorDescription":"Account's reward recipient doesn't match the pool's"}
```

The parser doesn't really care about status code, 403, 200, whatever, who needs status codes, and it just tries to extact JSON payload to see if it matches the expected response structure for a 'dl accepted' response kind. And here it fails to do even that, since it focuses its efforts on the JSON data in `Report-To:` header instead of the response body. Yeah, why follow HTTP protocol, when you can detect JSON data in the stream just by string-search for `{` character.

Since the problem is in the headers, most probably the same happens for 200/ok response. If the server returns any headers containing `{` character, it will cause the miner to misparse the response.

I can only say "that's not mine!" since it's been there in the code since at least c284151c2f8fd7f21c7d327c144b0bc41c79a122 network.cpp line 555 :)

Summarizing, the reason for this problem is: the response parser is **extraordinarily dumb**. I won't be replacing it with anything better anytime soon (neither the "retry asap" policy), but at least I should be able to improve current "payload finder" to handle headers better and that should do the trick.

**Comment by quetzalcoatl** [comment]
Alright.. that looks promising
![image](https://user-images.githubusercontent.com/1564880/100475008-439c7000-30e2-11eb-9247-0a73b0c6bad1.png)

**Comment by Zwurg** [comment]
Thanks for investigate the Problem.

Yes it makes sense that the error existed earlier, because the original blago miner also seems to have that problem, as I noticed in the Discord group of the pool.

But it looks good for Solving the error.

**Comment by mySebbe** [comment]
In the Miners Log the Problem still there.

22:13:54.694 *! GMI Burst: error parsing JSON message from pool: HTTP/1.1 200 OK\r\nDate: Sat, 20 Feb 2021 21:13:50 GMT\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 151\r\nConnection: close\r\nSet-Cookie: __cfduid=*********************************************; expires=Mon, 22-Mar-21 21:13:50 GMT; path=/; domain=.burstcoin.ro; HttpOnly; SameSite=Lax\r\nX-Ratelimit-Limit: 3\r\nX-Ratelimit-Remaining: 2\r\nX-Ratelimit-Reset: 1\r\nCF-Cache-Status: DYNAMIC\r\ncf-request-id: *******************************************\r\nReport-To: {"max_age":604800,"group":"cf-nel","endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=eLKUwpeD8bTKxm7puQ%%2FvyzPsRFxQURv4XluYaZgMXEYh5lOb%%2BE9HcjIuGYCMl9D5mjsOBUFBnOAQaStqPH9ErjJsn7zEBFyL8A8KjrHh6z1yXfCkjd0W"}]}\r\nNEL: {"report_to":"cf-nel","max_age":604800}\r\nServer: cloudflare\r\nCF-RAY: 624b3bdb78914bf5-AMS\r\nalt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400\r\n\r\n{"baseTarget":80482,"generationSignature":"c7e9d34da5a324083a8090c35c00f61e3ecd555716b9c60b9a398f99fafcf6f8","height":852957,"targetDeadline":31536000

**Comment by pir8radio** [comment]
@quetzalcoatl   I have blago miners reporting this issue on my pool..  I believe its related to myself and burstcoin.ro using cloudflare proxy.      Can you please help with one more release that can possibly ignore the response and just accept if buffer has anything at all in it?   maybe a config setting,  "bypassConfirm" or something?    I'm sure you dont really maintain this any longer.  I want my pool miners to be able to use blago they seem to like it.. i can send you some signa coin for the work.  :-)

My pool is:  https://signapool.notallmine.net    port 443
