### ISSUE TITLE
boom mine deadline not correct

### ISSUE THREAD

**Issue by landoyjx** [quetzalcoatl/blagominer#5]
boom mine deadline not correct

**Comment by landoyjx** [comment]
boom miner not work

**Comment by quetzalcoatl** [comment]
Yes it does! I mine it all the time, see screenshot, I made it just second ago, especially for you:

![image](https://user-images.githubusercontent.com/1564880/61362985-79d9a680-a883-11e9-99e8-be31dc95e76c.png)

This is from the latest version I've just published, so it certainly works.

If Boom mining does not work for you, then most probably you have something misconfigured in the `miner.conf` file. If the mining works, but the DLs are not accepted by the pool, then check the LOG file to see what was the response from the pool. If the DLs are rejected by the pool as "wrong", and the pool claims that the DLs are different, then check the LOG file and see if the mined that "wrong DL" at correct height and gensig.

In any case, you may zip & attach the `miner.conf` and/or the log file. Otherwise, I can't help you more, you've essentially not provided any details.

**Comment by quetzalcoatl** [comment]
Closing due to no response. Probably a configuration problem (#9 or similar)
