### ISSUE TITLE
BHD mining as POC1

### ISSUE THREAD

**Issue by holycow131415** [quetzalcoatl/blagominer#9]
**Describe the bug**
Burst mining is being mined as POC2. The BHD mining is being mined as POC1. I dont see anything in miner.config to change to make it switch to POC2 like there is for Burst.

**To Reproduce**
Run the miner.

**Expected behavior**
Plot files are POC2, so it should see POC2 on all coins and it works as expected on andzno's blago version.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by quetzalcoatl** [comment]
In `miner.conf` try adding this line to the coin's setup:
```
    "POC2StartBlock" : 0,                      // The block height PoC2 format started
```

Most probably, it's some dumb typo I made when refactoring. This setting should be 0 for all coins except BURST, and 502000 for BURST. If I made some typo, the 502000 default value might be activated for wrong coins, but if you set it via config file, your setting will take precedence, and it should fix it.

Thanks for reporting that, I'll review the code and make a patch in a few days, if life allows.

**Comment by holycow131415** [comment]
That seems to have fixed it. Whats weird is this isnt in andzno's config file.

**Comment by quetzalcoatl** [comment]
Yeah, it's not there because andzno's version was hardcoded, exploiting the fact there were only 2 coins: it used 502000 as default, and for second coin "BHD" it used 0. Or something like that. In n-mining version I tried to generalize it so it's reversed: 0 as default for any coin and exceptionally 502000 for coins which name looks like 'burst', but seems I've got a bug somewhere there.
